spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: ritik
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:oracle:thin:@Personal:1521:orcl
    username: c##ritik
